# Generated by Django 4.2.6 on 2023-12-14 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clienprove', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='campo_1',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='campo_2',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='campo_3',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='campo_4',
        ),
        migrations.AddField(
            model_name='factura',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='factura',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='producto',
            field=models.CharField(default='Producto', max_length=100),
        ),
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
